name: buildnotify-test
version: "1.0+git"
summary: A system tray based build status notification app for cctray.xml feed.
description: |
  BuildNotify is a system tray notification app for continuous integration build status changes.
grade: devel
confinement: devmode
base: core18
icon: icons/buildnotify.svg

apps:
  buildnotify:
    command: desktop-launch $SNAP/bin/buildnotifyapplet.py
    extensions:
      - kde-neon
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - network
      - home
      - opengl
    desktop: share/applications/buildnotify.desktop

environment:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

parts:
  buildnotify:
    plugin: python
    python-version: python3
    source: .
    build-packages:
      - python3
      - python3-pyqt5
      - python-keyring
      - execstack
    stage-packages:
      - libqt53dextras5
      - libqt53dquick5
      - libqt53danimation5
      - libqt53dquickscene2d5
      - libqt5webview5
      - libatk1.0-0
      - libgtk-3-0
      - libspeechd2
      - qtwebengine5-dev
    override-prime: |
      snapcraftctl prime
      sed -i 's|Icon=/usr/share/pixmaps/buildnotify.svg|Icon=${SNAP}/share/pixmaps/buildnotify.svg|g' share/applications/buildnotify.desktop
